name: 'news-action'
description: 'News bot'

inputs:
  DISCORD_WEBHOOK:
    description: 'WEBHOOK URL'
    required: true
  OPENWEATHER_APIKEY: 
    description: 'API_KEY'
    required: true


runs:
  using: 'composite'
  steps:
    - shell: bash
      id: setup
      run: |
        sudo apt update
        sudo apt autoremove -y
        sudo apt install -y python3
        sudo python3 -m pip install feedparser
        sudo python3 -m pip install requests
        sudo python3 -m pip install bs4

    - shell: bash
      id: news
      run: |
        cd ${{ github.action_path }}
        python3 news.py ${{ inputs.DISCORD_WEBHOOK }} ${{ inputs.OPENWEATHER_APIKEY }}
