name: 'News bot'

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:
    #  push:
    #    branches:
    #      - main

jobs:
  ubuntu-test:
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Set current datetime as env variable'
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME=$(date +'%Y/%m/%d(%a) %H:%M:%S')" >> $GITHUB_ENV

      - uses: k5-mot/news-action@main

      - name: 'A'
        run: |
          echo "NEWSLINE=$(cat news.txt)" >> $GITHUB_ENV

      - uses: sarisia/actions-status-discord@v1
        if: always() && ${{ env.DISCORD_WEBHOOK }} != null
        with:
          webhook: ${{ env.DISCORD_WEBHOOK }}
          title: 🦾 `${{ github.actor }}` - ニュース
          username: 'News Bot'
          avatar_url: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
          image: 'https://source.unsplash.com/random/2160x720?food'
          nocontext: true
          noprefix: true
          description: |
            `${{ env.NEWSLINE }}` 



# avatar_url: 'https://app.pixelencounter.com/api/basic/monsters/random/png?size=1000'
# image: 'https://pbs.twimg.com/profile_banners/1159383628951851008/1565318066/1080x360'

