name: 'News bot'

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:
    #  push:
    #    branches:
    #      - main

jobs:
  ubuntu-test:
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Set current datetime as env variable'
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME=$(date +'%Y/%m/%d(%a) %H:%M:%S')" >> $GITHUB_ENV

      - uses: k5-mot/news-action@main
        with:
          DISCORD_WEBHOOK: ${{ env.DISCORD_WEBHOOK }}
